// analysis/index.mjs — Block interface: graph analysis
export { betweenness, pagerank, louvain, tarjanSCC, topoSort, shortestPath, closeness, hits } from './algorithms.mjs'
export { computeCentrality, getCentralityStats, findBottlenecks } from './centrality.mjs'
export { detectCycles } from './cycles.mjs'
export { computeComplexity } from './complexity.mjs'
export { findHotPaths } from './hot-paths.mjs'
export { computeStats } from './stats.mjs'
export { detectViolations } from './violations.mjs'
export { detectClusters } from './cluster.mjs'
export { scoreEntryPoints } from './entry-point.mjs'
export { traceProcesses, loadEntryPointOverrides } from './process.mjs'
export { generateAdvice } from './advice.mjs'
export { detectDuplicateInstantiations } from './duplicates.mjs'
export { detectSchemaGaps } from './schema-gaps.mjs'
export { schemaAudit } from './schema-audit.mjs'
export { analyzeSchemaBlocks } from './schema-blocks.mjs'
